### ISSUE TITLE
Support all node configuration params

### ISSUE THREAD

**Issue by Nuttymoon** [Nuttymoon/ansible-avalanche-collection#5]
Use a generic way to declare node configuration params:
```yaml
avalanche_node_conf:
  "log-level": info
  ...
```
